### ISSUE TITLE
I'm getting following error

### ISSUE THREAD

**Issue by FlyFSX** [sergeyhartmann/streaming-link-generator#2]
Fatal error: Uncaught SergeyHartmann\StreamingLinkGenerator\GeneratorException: Effective URL not found. in /www/htdocs/w0188140/gamesnetworks.net/gdrive/vendor/sergeyhartmann/streaming-link-generator/src/StreamingLinkGenerator/Generator.php:85 Stack trace: #0 /www/htdocs/w0188140/gamesnetworks.net/gdrive/vendor/sergeyhartmann/streaming-link-generator/src/StreamingLinkGenerator/Generator.php(74): SergeyHartmann\StreamingLinkGenerator\Generator->buildLink(Object(GuzzleHttp\Psr7\Response)) #1 /www/htdocs/w0188140/gamesnetworks.net/gdrive/vendor/sergeyhartmann/streaming-link-generator/example/index.php(13): SergeyHartmann\StreamingLinkGenerator\Generator->generate('1mQbZNZ5N-X-Xnt...') #2 {main} thrown in /www/htdocs/w0188140/gamesnetworks.net/gdrive/vendor/sergeyhartmann/streaming-link-generator/src/StreamingLinkGenerator/Generator.php on line 85

**Comment by DonCorleone9** [comment]
Is this script working ?

**Comment by sergeyhartmann** [comment]
@FlyFSX hi
you are using SimpleCookieLoader?
make sure that the user who runs the script has read / write permission from the directory (for save and load cookies)

**Comment by minhman** [comment]
@FlyFSX are you pass that error?
