### ISSUE TITLE
Does this work anymore ?

### ISSUE THREAD

**Issue by DonCorleone9** [sergeyhartmann/streaming-link-generator#3]
Does this work anymore ?
Has anyone tried it in the recent past ?
Thanks.

**Comment by sergeyhartmann** [comment]
@DonCorleone9 hi. Yes it works.
![2018-12-23 1 04 02](https://user-images.githubusercontent.com/23013937/50378981-c4c56f80-064e-11e9-9354-caa3b2d3cb82.png)
