### ISSUE TITLE
Get error when stream large file size

### ISSUE THREAD

**Issue by minhman** [sergeyhartmann/streaming-link-generator#4]
Hello,
Your project is awesome. Clean, clear and very useful.
When video on google drive have small file size(10MB), it run normally.
Example: [https://xemphimchung.com/stream/example/?id=1M8g1lddi2Rj9JsDbS1yF3XCidP9i-2N1](https://xemphimchung.com/stream/example/?id=1M8g1lddi2Rj9JsDbS1yF3XCidP9i-2N1)
But when I used large video file (1.4GB), it return error.
`Fatal error: Uncaught SergeyHartmann\StreamingLinkGenerator\GeneratorException: Effective URL not found. in /public_html/stream/src/StreamingLinkGenerator/Generator.php:85 Stack trace: #0 /public_html/stream/src/StreamingLinkGenerator/Generator.php(74): SergeyHartmann\StreamingLinkGenerator\Generator->buildLink(Object(GuzzleHttp\Psr7\Response)) #1 /public_html/stream/example/index.php(18): SergeyHartmann\StreamingLinkGenerator\Generator->generate('1hjw5derCyD-6bP...') #2 {main} thrown in /public_html/stream/src/StreamingLinkGenerator/Generator.php on line 85`
Example: [https://xemphimchung.com/stream/example/?id=1hjw5derCyD-6bPLdQSYOFYyPOHDcDxcM](https://xemphimchung.com/stream/example/?id=1hjw5derCyD-6bPLdQSYOFYyPOHDcDxcM)
Follow issues #2, i have chmod to 777 to system that module Cookie Loader can work and generate g.cookie file. But still nothing happened.
I believe that stuck in scan for viruses and download anyway.
[https://prnt.sc/mlkseh](https://prnt.sc/mlkseh)
I have try a lot of way but I cant. Do you have any suggestion to pass that?
Please show me the way.
Many thanks!

**Comment by sergeyhartmann** [comment]
Hello,
Sorry for the long answer. 
I had no such problem. Please share that video and send me shareable link `https://drive.google.com/open?id=<FILE_ID>` (if still relevant). I will try to find out what is the matter.
